GET http://localhost:5757/comments
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMGIzZmZlMDYtYzMyNy00MjhiLTk2ZWItYTAyYzVhZGQ1N2M3IiwiaWF0IjoxNjY1ODI4MDgxfQ.M4h2aOn-QV_gd931kLA2CanALWs-wZpnOE6hAwiX9Cg